Simple Application Exercise/Fluffy Duffy Munchkin Cats/Fluffy Duffy Munchkin Cats/Models/Cat.cs
namespace Fluffy_Duffy_Munchkin_Cats.Models
{
    public class Cat
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public int Age { get; set; }

        public string Breed { get; set; }

        public string ImageUrl { get; set; }
    }
}

Simple Application Exercise/Fluffy Duffy Munchkin Cats/Fluffy Duffy Munchkin Cats/Models/ErrorViewModel.cs
using System;

namespace Fluffy_Duffy_Munchkin_Cats.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Simple Application Exercise/Fluffy Duffy Munchkin Cats/Fluffy Duffy Munchkin Cats/Controllers/CatsController.cs
namespace Fluffy_Duffy_Munchkin_Cats.Controllers
{
    using Data;
    using Microsoft.AspNetCore.Mvc;
    using Models;

    public class CatsController : Controller
    {
        public CatsController(FdmcContext context)
        {
            this.Context = context;
        }

        public FdmcContext Context { get; set; }

        public IActionResult Details(int id)
        {
            var cat = this.Context.Cats.Find(id);
            if (cat == null)
            {
                return NotFound();
            }
            return View(cat);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Cat model)
        {
            this.Context.Cats.Add(model);
            this.Context.SaveChanges();
            return Redirect("/Cats/Details/"+model.Id);
        }
    }
}

Simple Application Exercise/Fluffy Duffy Munchkin Cats/Fluffy Duffy Munchkin Cats/Controllers/HomeController.cs
namespace Fluffy_Duffy_Munchkin_Cats.Controllers
{
    using Data;
    using Microsoft.AspNetCore.Mvc;
    using System.Linq;

    public class HomeController : Controller
    {
        public HomeController(FdmcContext context)
        {
            this.Context = context;
        }

        public FdmcContext Context { get; private set; }

        public IActionResult Index()
        {
            var cats = this.Context.Cats.ToList();
            return View(cats);
        }
    }
}

Simple Application Exercise/Fluffy Duffy Munchkin Cats/Fluffy Duffy Munchkin Cats/Views/Cats/Add.cshtml
@using Fluffy_Duffy_Munchkin_Cats.Models;
@model Cat

@{
    ViewData["Title"] = "Add";
}

<h2>Add Cat</h2>
<form action="/Cats/Add" method="POST">

    <p>
        <label asp-for="Name"></label>
        <input type="text" name="Name" value="" />
    </p>
    <p>
        <label asp-for="Age"></label>
        <input type="text" name="Age" value="" />
    </p>
    <p>
        <label asp-for="Breed"></label>
        <input type="text" name="Breed" value="" />
    </p>
    <p>
        <label asp-for="ImageUrl"></label>
       <input type="text" name="ImageUrl" value="" />
    </p>
    <p>
        <input type="submit" value="Add Cat" />
    </p>
</form>

Simple Application Exercise/Fluffy Duffy Munchkin Cats/Fluffy Duffy Munchkin Cats/Views/Cats/Details.cshtml
@using Fluffy_Duffy_Munchkin_Cats.Models;
@model Cat
@{
    ViewData["Title"] = "Details";
}
<h1>@Model.Name</h1>

<img src="@Model.ImageUrl" alt="Picture for @Model.Name" style="max-width: 300px" ) />

<p><strong>Age: </strong>@Model.Age</p>

<p><strong>Breed: </strong>@Model.Breed</p>

Simple Application Exercise/Fluffy Duffy Munchkin Cats/Fluffy Duffy Munchkin Cats/Views/Home/Index.cshtml
@using Fluffy_Duffy_Munchkin_Cats.Models;

@model IEnumerable<Cat>

@{
    ViewData["Title"] = "Home";
}

<h1>Fluffy Duffy Muchkin Cats</h1>
<ul>
    @foreach (var cat in Model)
    {

        <li><a asp-controller="Cats" asp-action="Details" asp-route-id="@cat.Id">@cat.Name</a></li>
    }
</ul>
       
<a asp-controller="Cats" asp-action="Add">Add a Cat</a>

Simple Application Exercise/Fluffy Duffy Munchkin Cats/Fluffy Duffy Munchkin Cats/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8"/>
    <title>@ViewData["Title"] - Fluffy Duffy Munchkin Cats</title>
</head>
<body>
                                  @RenderBody()
</body>
</html>